


#LASER CO2 FRACCIONAL
#LASER CO2 FRACCIONAL + BOTOX
#LASER CO2 FRACCIONAL + ACIDO HIALURONICO (TEOSYAL DEEP LINES)
#LASER CO2 FRACCIONAL + BOTOX + ACIDO HIALURONICO (TEOSYAL DEEP LINES)

#QUICKLASER + BOTOX
#QUICKLASER + ACIDO HIALURONICO (TEOSYAL DEEP LINES)
#QUICKLASER + BOTOX + ACIDO HIALURONICO (TEOSYAL DEEP LINES)

#LASER CO2 FRACCIONAL + NCTF 3 Sesiones
#LASER CO2 FRACCIONAL + NCTF 5 Sesiones

#LASER CO2 FRACCIONAL + QUICKLASER
#LASER TRIACTIVE + CARBOXITERAPIA

#PUNTA DE DIAMANTES
#CARBOXITERAPIA


# Treatment
_treatment_list = [


('LASER CO2 FRACCIONAL',	'LASER CO2 FRACCIONAL'),
('LASER CO2 FRACCIONAL + BOTOX',	'LASER CO2 FRACCIONAL + BOTOX'),
('LASER CO2 FRACCIONAL + ACIDO HIALURONICO (TEOSYAL DEEP LINES)',	'LASER CO2 FRACCIONAL + ACIDO HIALURONICO (TEOSYAL DEEP LINES)'),
('LASER CO2 FRACCIONAL + BOTOX + ACIDO HIALURONICO (TEOSYAL DEEP LINES)',	'LASER CO2 FRACCIONAL + BOTOX + ACIDO HIALURONICO (TEOSYAL DEEP LINES)'),

('QUICKLASER + BOTOX',	'QUICKLASER + BOTOX'),
('QUICKLASER + ACIDO HIALURONICO (TEOSYAL DEEP LINES)',	'QUICKLASER + ACIDO HIALURONICO (TEOSYAL DEEP LINES)'),
('QUICKLASER + BOTOX + ACIDO HIALURONICO (TEOSYAL DEEP LINES)',	'QUICKLASER + BOTOX + ACIDO HIALURONICO (TEOSYAL DEEP LINES)'),

('LASER CO2 FRACCIONAL + NCTF 3 Sesiones',	'LASER CO2 FRACCIONAL + NCTF 3 Sesiones'),
('LASER CO2 FRACCIONAL + NCTF 5 Sesiones',	'LASER CO2 FRACCIONAL + NCTF 5 Sesiones'),

('LASER CO2 FRACCIONAL + QUICKLASER',	'LASER CO2 FRACCIONAL + QUICKLASER'),
('LASER TRIACTIVE + CARBOXITERAPIA',	'LASER TRIACTIVE + CARBOXITERAPIA'),

('PUNTA DE DIAMANTES',	'PUNTA DE DIAMANTES'),
('CARBOXITERAPIA',	'CARBOXITERAPIA'),

]

