

# Treatment
_treatment_list = [

('ECOGRAFIAS SIMPLES',	'ECOGRAFIAS SIMPLES'),
('ECOGRAFIAS GINECOLOGICAS Y OBSTETRICAS',	'ECOGRAFIAS GINECOLOGICAS Y OBSTETRICAS'),
('ECOGRAFIAS OBSTETRICAS ESPECIALES',	'ECOGRAFIAS OBSTETRICAS ESPECIALES'),
('ECOGRAFIAS PARTES BLANDAS',	'ECOGRAFIAS PARTES BLANDAS'),
('ECOGRAFIAS MUSCULOESQUELETICAS',	'ECOGRAFIAS MUSCULOESQUELETICAS'),
('ECOGRAFIAS ESPECIALES',	'ECOGRAFIAS ESPECIALES'),
('ECOGRAFIAS ESPECIALES DOPPLER COLOR',	'ECOGRAFIAS ESPECIALES DOPPLER COLOR'),
('ECOGRAFIAS ESPECIALES MORFOLOGICAS + DOPPLER COLOR',	'ECOGRAFIAS ESPECIALES MORFOLOGICAS + DOPPLER COLOR'),

]


_zone_list = [
('Indeterminada',	'Indeterminada'),
]

_pathology_list = [
('Indeterminada',	'Indeterminada'),
]

_sessions_list = [
('1 sesion',	'1 sesion'),
]

_level_list = [
]

_time_list = [
]
