	_zone_list = [ 
		('face_all','Todo Rostro'), 
		('cheekbones','Pómulos'), 
		('neck','Cuello'), 
		('hands','Manos'), 
		('face_local','Localizado Rostro'), 
		('body_local','Localizado Cuerpo'), 
		('vagina','Vagina'), 
		('face_neck','PAQUETE Rejuvenecimiento 1 (Rostro + Cuello)'), 
		('face_hands','PAQUETE Rejuvenecimiento 2 (Rostro + Manos)'), 
		('face_neck_hands','PAQUETE Rejuvenecimiento 3 (Rostro + Cuello + Manos)'),   
		('belly','Abdomen'), 
		('areolas','Ariolas'), 
		('armpits','Axilas'), 
		('arms','Brazos'), 
		('back','Espalda'), 
		('gluteus','Gluteos'), 
		('shoulders','Hombros'), 
		('breast','Pecho'), 
		('legs','Piernas'), 
		('feet','Pies'), 
		('face','Rostro') 
	]