mv *.pyc ./pyc/. 
mv account/*.pyc ./pyc/.
mv containers/*.pyc ./pyc/.
mv electronic/*.pyc ./pyc/.
mv emr/*.pyc ./pyc/.
mv libs/*.pyc ./pyc/.
mv management/*.pyc ./pyc/.
mv marketing/*.pyc ./pyc/.
mv order/*.pyc ./pyc/.
mv patient/*.pyc ./pyc/.
mv service/*.pyc ./pyc/.
